<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>fileTypes</key>
    <array>
    </array>
    <key>name</key>
    <string>Find_Symbols_Panel</string>
    <key>patterns</key>
    <array>
        <dict>
            <key>comment</key>
            <string>Position</string>
            <key>match</key>
            <string>^.*:\d+</string>
            <key>name</key>
            <string>string.quoted.double.c</string>
        </dict>
        <dict>
            <key>comment</key>
            <string>CodeLine</string>
            <key>match</key>
            <string>\s*.+$</string>
        </dict>
    </array>
    <key>scopeName</key>
    <string>text.sublimeclang</string>
</dict>
</plist>
